name: Fly Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://igknite.fly.dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only --no-cache --strategy immediate